---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install packages
  ansible.builtin.include_tasks: install.yml

- name: Join domain
  ansible.builtin.include_tasks: domain-join.yml

- name: Configure SSSD
  ansible.builtin.include_tasks: sssd.yml

- name: Optional steps
  ansible.builtin.include_tasks: optional.yml
