---
- name: Gather distribution facts
  when:
    - ansible_distribution is not defined or
      ansible_distribution_major_version is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - distribution_major_version
      - distribution_release
      - os_family

- name: Validate EL version
  when:
    - ansible_os_family == 'RedHat'
  ansible.builtin.assert:
    that:
      - ansible_distribution_major_version in _domjoin_supported_el_major_versions
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported. Supported versions are: {{ _domjoin_supported_el_major_versions | join(', ') }}"
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is supported."

- name: Validate non-EL distribution
  when:
    - ansible_os_family != 'RedHat'
  ansible.builtin.assert:
    that:
      - ansible_distribution in _domjoin_supported_non_el_distributions
    fail_msg: "{{ ansible_distribution }} is not supported. Supported distributions are: {{ _domjoin_supported_non_el_distributions | join(', ') }}"
    success_msg: "Some {{ ansible_distribution }} releases are supported."
