---
namespace: trippsc2
name: ad
version: '1.2.0'
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains modules and roles for configuring Active Directory.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.windows: ">=1.5.0"
  community.hashi_vault: ">=4.2.0"
  community.windows: ">=1.11.0"
  microsoft.ad: ">=1.0.0"
  trippsc2.hashi_vault: ">=1.0.0"
  trippsc2.windows: ">=1.0.0"

repository: https://github.com/trippsc2/ansible-collection-ad.git

build_ignore:
  - .gitignore
