---
namespace: trippsc2
name: ad
version: 2.4.1
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains modules and roles for configuring Active Directory.

license_file: 'LICENSE'

tags:
  - infrastructure
  - windows

dependencies:
  ansible.windows: ">=2.7.0"
  community.hashi_vault: ">=2.5.0"
  community.windows: ">=2.7.0"
  microsoft.ad: ">=1.0.0"
  trippsc2.hashi_vault: ">=1.0.0"
  trippsc2.windows: ">=1.0.0"

repository: https://github.com/trippsoft/ansible-collection-ad.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
