---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: existingdc
    box: jtarpley/w2025_cis
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: ad_domain_controller_
    groups:
      - windows
  - name: dc
    box: jtarpley/${MOLECULE_BOX:-w2025_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: ad_domain_controller_
    groups:
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
        ansible_password: vagrant
    host_vars:
      dc:
        ansible_user: TEST\vagrant
        ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o StrictHostKeyChecking=no'
        dc_domain_name: test.loc
        dc_domain_admin_user: vagrant@test.loc
        dc_domain_admin_password: vagrant
        dc_dns_forwarders:
          - '8.8.8.8'
          - '4.2.2.2'
        dc_dns_servers:
          - "{{ hostvars['existingdc'].ansible_host }}"
          - '127.0.0.1'
        dc_safe_mode_password: SecurePassword123!
        dc_is_domain_naming_master: true
        dc_is_schema_master: true
        dc_is_infrastructure_master: true
        dc_is_pdc_emulator: true
        dc_is_rid_master: true
      existingdc:
        ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o StrictHostKeyChecking=no'
verifier:
  name: ansible
