---
- name: Prepare existing DC
  hosts:
    - existingdc
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare new DC
  hosts:
    - dc
  gather_facts: false
  roles:
    - role: trippsc2.ad.testing_win_member
      vars:
        dc_inventory_name: existingdc
