---
- name: Prepare existing DC
  hosts:
    - existingdc
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare new DC
  hosts:
    - dc
  gather_facts: false
  pre_tasks:
    - name: Disable IPv6
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Services\TCPIP6\Parameters
        name: DisabledComponents
        data: 255
        type: dword
      vars:
        ansible_user: vagrant
      notify:
        - _reboot_windows

  roles:
    - role: trippsc2.ad.testing_win_member
      vars:
        dc_inventory_name: existingdc

  handlers:
    - name: Reboot
      listen: _reboot_windows
      ansible.windows.win_reboot:
        reboot_timeout: 300
        msg: Reboot initiated to disable IPv6
        post_reboot_delay: 30
        connect_timeout: 30
      vars:
        ansible_user: vagrant
