---
argument_specs:
  main:
    short_description: Domain Controller
    description:
      - This role configures the Windows Server machine as an Active Directory Domain Controller.
    author: Jim Tarpley
    options:
      vault_url:
        type: str
        required: false
        description:
          - The URL for accessing HashiCorp Vault.
          - Alternatively, this can be configured through ansible.cfg or environment variables.
      vault_token:
        type: str
        required: false
        description:
          - The token for accessing HashiCorp Vault.
          - Alternatively, this (or any other authentication method) can be configured through ansible.cfg or environment variables.
      dc_vault_create_mount_point:
        type: bool
        required: false
        default: true
        description:
          - Whether to create the KV version 2 mount point in HashiCorp Vault for the safe mode password, if it doesn't exist.
      dc_vault_managed_safe_mode_password:
        type: bool
        required: false
        default: true
        description:
          - Whether to manage the safe mode password in HashiCorp Vault.
      dc_vault_safe_mode_mount_point:
        type: str
        required: false
        default: os
        description:
          - The KV version 2 mount point in HashiCorp Vault for storing the safe mode password.
      dc_vault_safe_mode_path:
        type: str
        required: false
        default: "{{ inventory_hostname }}/safe_mode"
        description:
          - The path within the KV version 2 mount point in HashiCorp Vault for storing the safe mode password.
      dc_safe_mode_password:
        type: str
        required: false
        description:
          - The safe mode password for the domain controller.
          - If *dc_vault_managed_safe_mode_password* is `true`, this is required.
          - If *dc_vault_managed_safe_mode_password* is `false` and the secret is already stored in HashiCorp Vault, this is ignored.
          - If *dc_vault_managed_safe_mode_password* is `false` and the secret is not stored in HashiCorp Vault, this password used and stored in HashiCorp Vault.
      dc_first_domain_controller:
        type: bool
        required: false
        default: false
        description:
          - Whether the server is the first domain controller in the domain.
      dc_domain_name:
        type: str
        required: true
        description:
          - The name of the domain for which the server will serve as domain controller.
      dc_domain_admin_user:
        type: str
        required: false
        description:
          - The user account to use for configuring the domain controller.
          - If *dc_first_domain_controller* is `true`, this is ignored.
          - Otherwise, this is required and the user account must have the necessary permissions to promote the server to a domain controller.
      dc_domain_admin_password:
        type: str
        required: false
        description:
          - The password for the *dc_domain_admin_user* user account.
      dc_database_path:
        type: path
        required: false
        default: C:\Windows\NTDS
        description:
          - The path to the database files for the domain controller.
      dc_domain_log_path:
        type: path
        required: false
        default: C:\Windows\Logs
        description:
          - The path to the log files for the domain controller.
      dc_sysvol_path:
        type: path
        required: false
        default: C:\Windows\SYSVOL
        description:
          - The path to the SYSVOL files for the domain controller.
      dc_dns_forwarders:
        type: list
        required: false
        default:
          - '8.8.8.8'
          - '4.2.2.2'
        elements: str
        description:
          - A list of DNS forwarder IP addresses for the domain controller.
      dc_dns_servers:
        type: list
        required: true
        elements: str
        description:
          - A list of DNS server IP addresses for the domain controller.
      dc_is_domain_naming_master:
        type: bool
        required: false
        default: false
        description:
          - Whether the domain controller should hold the Domain Naming Master FSMO role.
      dc_is_schema_master:
        type: bool
        required: false
        default: false
        description:
          - Whether the domain controller should hold the Schema Master FSMO role.
      dc_is_infrastructure_master:
        type: bool
        required: false
        default: false
        description:
          - Whether the domain controller should hold the Infrastructure Master FSMO role.
      dc_is_pdc_emulator:
        type: bool
        required: false
        default: false
        description:
          - Whether the domain controller should hold the PDC Emulator FSMO role.
      dc_is_rid_master:
        type: bool
        required: false
        default: false
        description:
          - Whether the domain controller should hold the RID Master FSMO role.
