---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: domain_controller
  description: |
    This role configures the Windows Server machine as an Active Directory Domain Controller.
    
    The following scenarios are supported:
    - The server is the first domain controller in a new forest.
    - The server is an additional domain controller in an existing domain.
    
    The following scenarios are not supported, but may be added in the future:
    - The server is the first domain controller in a child or tree domain in an existing forest.

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.hashi_vault
  - community.windows
  - microsoft.ad
  - trippsc2.hashi_vault
  - trippsc2.windows

dependencies:
  - role: trippsc2.windows.install_psgallery
