---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: domain_controller
  description: This role configures the Windows Server machine as an Active Directory Domain Controller.

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.hashi_vault
  - community.windows
  - microsoft.ad
  - trippsc2.hashi_vault
  - trippsc2.windows

dependencies: []
