---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: dc
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: domain_controller_new_
    groups:
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
    host_vars:
      dc:
        dc_first_domain_controller: true
        dc_domain_name: test.loc
        dc_domain_admin_user: vagrant@test.loc
        dc_domain_admin_password: vagrant
        dc_dns_forwarders:
          - '8.8.8.8'
          - '4.2.2.2'
        dc_dns_servers:
          - '127.0.0.1'
        dc_safe_mode_password: SecurePassword123!
verifier:
  name: ansible
