---
- name: Verify
  hosts:
    - dc
  tasks:
    - name: Verify that the domain controller is promoted
      ansible.builtin.assert:
        that:
          - ("domain controller" in ansible_windows_domain_role)
          - ansible_windows_domain == 'test.loc'
        fail_msg: The domain controller is not promoted.
        success_msg: The domain controller is promoted.

    - name: Check DNS forwarders
      ansible.windows.win_powershell:
        script: |
          $Ansible.Changed = $false
          $dnsForwarders = Get-DnsServerForwarder -ComputerName DC

          $Ansible.Result = ($dnsForwarders.IPAddress[0] -eq '8.8.8.8' -and $dnsForwarders.IPAddress[1] -eq '4.2.2.2')
      register: _powershell

    - name: Verify DNS forwarders
      ansible.builtin.assert:
        that:
          - _powershell.result
        fail_msg: The DNS forwarders are not correct.
        success_msg: The DNS forwarders are correct.
