---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: testing_win_member
  description: This role joins a Windows machine to a test Active Directory Domain during Molecule testing.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Windows
    versions:
      - all

collections:
  - ansible.windows
  - community.windows
  - microsoft.ad

dependencies: []
