---
- name: Ensure 'DnsServerDsc' PowerShell module is installed
  community.windows.win_psmodule:
    name: DnsServerDsc
    state: present

- name: Ensure 'ActiveDirectoryDsc' PowerShell module is installed
  community.windows.win_psmodule:
    name: ActiveDirectoryDsc
    state: present

- name: Install DNS management features
  ansible.windows.win_feature:
    name:
      - RSAT-DNS-Server
    include_sub_features: true
    state: present
