---
- name: Prepare new DC
  hosts:
    - dc
  gather_facts: false
  tasks:
    - name: Disable IPv6
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Services\TCPIP6\Parameters
        name: DisabledComponents
        data: 255
        type: dword
      notify:
        - _reboot_windows

  handlers:
    - name: Reboot
      listen: _reboot_windows
      ansible.windows.win_reboot:
        reboot_timeout: 300
        msg: Reboot initiated to disable IPv6
        post_reboot_delay: 30
        connect_timeout: 30
