---
galaxy_info:
    author: Jim Tarpley
    namespace: trippsc2
    role_name: linux_member
    description: This role joins a Linux machine to a Windows domain.
    license: MIT

    min_ansible_version: '2.14'

    platforms:
      - name: Debian
        versions:
          - bullseye
          - bookworm
      - name: EL
        versions:
          - '8'
          - '9'
      - name: Ubuntu
        versions:
          - focal
          - jammy
          - noble

collections:
  - community.general

dependencies: []
