---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: linux_member
  description: |
    This role joins a Linux system to an Active Directory domain.
    
    Before running this role, the system should use be able to resolve the AD domain name and domain controllers via DNS.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy

collections:
  - community.general

dependencies: []
