---
dc_inventory_name: dc
dc_ip_address: "{{ hostvars[dc_inventory_name].ansible_host }}"

domain_name: test.loc
domain_join_username: vagrant
domain_join_password: vagrant

dns_register_host: true
dns_ip_address: "{{ ansible_host }}"
