---
_domjoin_is_os_supported: true
_domjoin_is_tested: false

_domjoin_packages:
  - adcli
  - libnss-sss
  - libpam-sss
  - oddjob
  - oddjob-mkhomedir
  - packagekit
  - python3-pexpect
  - realmd
  - samba-common-bin
  - sssd
  - sssd-tools

_domjoin_ssh_service: sshd.service
