---
argument_specs:
  main:
    short_description: Join Testing Active Directory Domain
    description:
      - This role joins a Linux machine to a test Active Directory Domain during Molecule testing.
    author: Jim Tarpley (@trippsc2)
    options:
      dc_inventory_name:
        type: str
        required: false
        default: dc
        description:
          - The Ansible inventory name of the test domain controller.
      dc_ip_address:
        type: str
        required: false
        default: "{{ hostvars[dc_inventory_name].ansible_host }}"
        description:
          - The IP address of the test domain controller.
      domain_name:
        type: str
        required: false
        default: test.loc
        description:
          - The name of the domain to join.
      domain_join_username:
        type: str
        required: false
        default: vagrant
        description:
          - The username to use to join the domain.
      domain_join_password:
        type: str
        required: false
        default: vagrant
        no_log: true
        description:
          - The password to use to join the domain.
      domain_join_hostname:
        type: str
        required: false
        default: "{{ inventory_hostname }}"
        description:
          - The hostname of the joining machine.
      dns_register_host:
        type: bool
        required: false
        default: true
        description:
          - Whether to register the hostname in DNS.
      dns_ip_address:
        type: str
        required: false
        default: "{{ ansible_host }}"
        description:
          - The IP address to register in DNS.
      dns_register_reverse_host:
        type: bool
        required: false
        default: true
        description:
          - Whether to register the reverse hostname in DNS.
      dns_reverse_zone:
        type: str
        required: false
        default: >-
          {{ (dns_ip_address | split('.'))[2] }}.{{ (dns_ip_address | split('.'))[1] }}.{{ (dns_ip_address | split('.'))[0] }}.in-addr.arpa
        description:
          - The reverse DNS zone to register the reverse hostname in.
      dns_reverse_name:
        type: str
        required: false
        default: "{{ (dns_ip_address | split('.'))[3] }}"
        description:
          - The reverse DNS name to register.
      dns_reverse_value:
        type: str
        required: false
        default: "{{ inventory_hostname }}.{{ domain_name }}"
        description:
          - The reverse DNS value to register.
