---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: rotate_ad_user_password
  description: This role rotates the password for an Active Directory user.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Windows
    versions:
      - '2025'
      - '2022'
      - '2019'

collections:
  - ansible.windows
  - community.hashi_vault
  - community.windows
  - microsoft.ad
  - trippsc2.hashi_vault

dependencies: []
