---
argument_specs:
  main:
    short_description: Create Testing Active Directory Domain
    description:
      - This role creates an Active Directory domain on the Windows machine for use during Molecule testing.
    author: Jim Tarpley (@trippsc2)
    options:
      configure_reverse_lookup_zone:
        type: bool
        required: false
        default: true
        description:
          - Whether to configure the reverse lookup zone for the domain.
      dc_initial_dns_servers:
        type: list
        required: false
        default: 
          - '8.8.8.8'
          - '1.1.1.1'
        elements: str
        description:
          - List of initial DNS servers to use when creating the domain.
      domain_name:
        type: str
        required: false
        default: test.loc
        description:
          - The name of the domain to create.
      dc_safe_mode_password:
        type: str
        required: false
        default: SecurePassword123!
        no_log: true
        description:
          - The password to use for the domain in safe mode.
      dc_domain_admin_username:
        type: str
        required: false
        default: vagrant
        description:
          - The username to which to give all administrative rights for the domain.
      dc_domain_admin_password:
        type: str
        required: false
        no_log: true
        description:
          - The password for the domain admin user.
          - If not provided, the domain admin user must already exist.
      domain_base_dn:
        type: str
        required: false
        default: DC=test,DC=loc
        description:
          - The base DN for the domain.
      dc_reverse_lookup_zone_network_id:
        type: str
        required: false
        default: "{{ ansible_host | ansible.utils.ipsubnet(24) }}"
        description:
          - The network ID for the reverse lookup zone to create.
      dc_reverse_lookup_zone_name:
        type: str
        required: false
        default: "{{ (ansible_host | split('.'))[1] }}.{{ (ansible_host | split('.'))[0] }}.in-addr.arpa"
        description:
          - The name of the reverse lookup zone to create.
      dc_reverse_lookup_zone_data:
        type: str
        required: false
        default: "{{ (ansible_host | split('.'))[3] }}.{{ (ansible_host | split('.'))[2] }}"
        description:
          - The data for the reverse lookup zone.
