---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: testing_domain_controller
  description: This role creates an Active Directory domain on the Windows machine for use during Molecule testing.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Windows
    versions:
      - '2025'
      - '2022'
      - '2019'

collections:
  - ansible.windows
  - community.windows
  - microsoft.ad

dependencies: []
