---
- name: Ensure 'xDhcpServer' PowerShell module is installed
  community.windows.win_psmodule:
    name: xDhcpServer
    accept_license: true
    state: present

- name: Install DHCP Server management tools feature
  ansible.windows.win_feature:
    name:
      - RSAT-DHCP
    state: present
