---
- name: Gather OS facts
  when:
    - ansible_distribution is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - os_family

- name: Validate Windows Server
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Windows'
      - ('Windows Server' in ansible_distribution)
    fail_msg: "This role can only be run on a Windows Server system.  {{ ansible_distribution }} is not supported."
    success_msg: "This role is running on {{ ansible_distribution }}."

- name: Validate DHCP DNS Name
  loop: "{{ dhcp_authorize_servers }}"
  loop_control:
    label: "{{ item.dns_name }}"
  ansible.builtin.assert:
    that:
      - item.dns_name is community.general.fqdn_valid
    fail_msg: "{{ item.dns_name }} is not a valid FQDN."
    success_msg: "{{ item.dns_name }} is a valid FQDN."

- name: Validate DHCP IP Address
  loop: "{{ dhcp_authorize_servers }}"
  loop_control:
    label: "{{ item.ip_address }}"
  ansible.builtin.assert:
    that:
      - item.ip_address is ansible.utils.ipv4
    fail_msg: "{{ item.ip_address }} is not a valid IPv4 address."
    success_msg: "{{ item.ip_address }} is a valid IPv4 address." 
