---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: authorize_dhcp_server
  description: This role authorizes a domain member as a DHCP Server in Active Directory.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.utils
  - ansible.windows
  - community.general
  - community.windows
  - trippsc2.windows

dependencies:
  - role: trippsc2.windows.install_psgallery
