---
argument_specs:
  main:
    short_description: Configure Standalone Server DNS to Testing Active Directory Domain
    description:
      - This role configures DNS on a standalone (non-domain) Windows machine to use the domain controller for DNS and registers its IP address in DNS.
    author: Jim Tarpley (@trippsc2)
    options:
      dc_inventory_name:
        type: str
        required: false
        default: dc
        description:
          - The Ansible inventory name of the test domain controller.
      dc_ip_address:
        type: str
        required: false
        default: "{{ hostvars[dc_inventory_name].ansible_host }}"
        description:
          - The IP address of the test domain controller.
      domain_name:
        type: str
        required: false
        default: test.loc
        description:
          - The name of the domain to join.
      dns_host_name:
        type: str
        required: false
        default: "{{ inventory_hostname }}"
        description:
          - The hostname of the DNS server.
      dns_ip_address:
        type: str
        required: false
        default: "{{ ansible_host }}"
        description:
          - The IP address of the DNS server.
