---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  role_name: testing_standalone_win
  description: This role configures DNS on a standalone (non-domain) Windows machine to use the domain controller for DNS and registers its IP address in DNS.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Windows
    versions:
      - all

collections:
  - ansible.windows

dependencies: []
