---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller
  tasks:
    - name: Create new organizational unit
      microsoft.ad.ou:
        name: Linux
        state: present

- name: Prepare
  hosts:
    - subjects
  pre_tasks:
    - name: Set DNS server on all interfaces to DC
      become: true
      ansible.builtin.copy:
        content: |
          nameserver {{ hostvars['dc'].ansible_host }}
          search {{ domjoin_domain_name }}
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
