---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller
  tasks:
    - name: Create new organizational unit
      microsoft.ad.ou:
        name: Linux
        state: present

- name: Prepare
  hosts:
    - subjects
  pre_tasks:
    - name: Bootstrap python for Ansible
      become: true
      ansible.builtin.raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal)) ||
        (test -e /usr/bin/yum && sudo yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && sudo /usr/sbin/pkg_add -U -I -x python%3.7) ||
        echo "Warning: Python not bootstrapped due to unknown platform."
        )
      changed_when: false

    - name: Set DNS server on all interfaces to DC
      become: true
      ansible.builtin.copy:
        content: |
          nameserver {{ hostvars['dc'].ansible_host }}
          search {{ domjoin_domain_name }}
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
