---
non_domain_user: vagrant

dc_inventory_name: dc
dc_ip_address: "{{ hostvars[dc_inventory_name].ansible_host }}"

domain_name: test.loc
domain_join_username: "vagrant@{{ domain_name }}"
domain_join_password: vagrant
domain_join_hostname: "{{ inventory_hostname }}"

dc_copy_ssh_key_from_local_user: true

dns_register_host: true
dns_ip_address: "{{ ansible_host }}"

dns_register_reverse_host: true
dns_reverse_zone: >-
  {{ (dns_ip_address | split('.'))[2] }}.{{ (dns_ip_address | split('.'))[1] }}.{{ (dns_ip_address | split('.'))[0] }}.in-addr.arpa
dns_reverse_name: "{{ (dns_ip_address | split('.'))[3] }}"
dns_reverse_value: "{{ inventory_hostname }}.{{ domain_name }}"
