---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/authorize_dhcp_server/.aar_doc.yml
      - roles/authorize_dhcp_server/README.md
      - roles/authorize_dhcp_server/meta/argument_specs.yml
      - roles/authorize_dhcp_server/meta/main.yml
      - roles/domain_controller/.aar_doc.yml
      - roles/domain_controller/README.md
      - roles/domain_controller/meta/argument_specs.yml
      - roles/domain_controller/meta/main.yml
      - roles/linux_member/.aar_doc.yml
      - roles/linux_member/README.md
      - roles/linux_member/meta/argument_specs.yml
      - roles/linux_member/meta/main.yml
      - roles/rotate_ad_user_password/.aar_doc.yml
      - roles/rotate_ad_user_password/README.md
      - roles/rotate_ad_user_password/meta/argument_specs.yml
      - roles/rotate_ad_user_password/meta/main.yml
      - roles/testing_domain_controller/.aar_doc.yml
      - roles/testing_domain_controller/README.md
      - roles/testing_domain_controller/meta/argument_specs.yml
      - roles/testing_domain_controller/meta/main.yml
      - roles/testing_linux_member/.aar_doc.yml
      - roles/testing_linux_member/README.md
      - roles/testing_linux_member/meta/argument_specs.yml
      - roles/testing_linux_member/meta/main.yml
      - roles/testing_standalone_win/.aar_doc.yml
      - roles/testing_standalone_win/README.md
      - roles/testing_standalone_win/meta/argument_specs.yml
      - roles/testing_standalone_win/meta/main.yml
      - roles/testing_win_member/.aar_doc.yml
      - roles/testing_win_member/README.md
      - roles/testing_win_member/meta/argument_specs.yml
      - roles/testing_win_member/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.adcs'
jobs:
  docs_authorize_dhcp_server:
    name: Generate authorize_dhcp_server role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'authorize_dhcp_server'
  docs_domain_controller:
    name: Generate domain_controller role documentation
    permissions:
      contents: write
    needs: docs_authorize_dhcp_server
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'domain_controller'
  docs_linux_member:
    name: Generate linux_member role documentation
    permissions:
      contents: write
    needs: docs_domain_controller
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'linux_member'
  docs_rotate_ad_user_password:
    name: Generate rotate_ad_user_password role documentation
    permissions:
      contents: write
    needs: docs_linux_member
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'rotate_ad_user_password'
  docs_testing_domain_controller:
    name: Generate testing_domain_controller role documentation
    permissions:
      contents: write
    needs: docs_rotate_ad_user_password
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_domain_controller'
  docs_testing_linux_member:
    name: Generate testing_linux_member role documentation
    permissions:
      contents: write
    needs: docs_testing_domain_controller
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_linux_member'
  docs_testing_standalone_win:
    name: Generate testing_standalone_win role documentation
    permissions:
      contents: write
    needs: docs_testing_linux_member
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_standalone_win'
  docs_testing_win_member:
    name: Generate testing_win_member role documentation
    permissions:
      contents: write
    needs: docs_testing_standalone_win
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_win_member'
