---
name: Generate Role Docs - domain_controller role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-domain_controller.yml
      - roles/domain_controller/.aar_doc.yml
      - roles/domain_controller/meta/argument_specs.yml
      - roles/domain_controller/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  docs:
    name: Generate domain_controller role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'domain_controller'
