---
name: Generate Role Docs - testing_domain_controller role
'on':
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-testing_domain_controller.yml
      - galaxy.yml
      - roles/testing_domain_controller/.aar_doc.yml
      - roles/testing_domain_controller/meta/argument_specs.yml
      - roles/testing_domain_controller/meta/main.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-testing_domain_controller.yml
      - galaxy.yml
      - roles/testing_domain_controller/.aar_doc.yml
      - roles/testing_domain_controller/meta/argument_specs.yml
      - roles/testing_domain_controller/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  docs:
    name: Generate testing_domain_controller role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_domain_controller'
