---
name: Generate Role Docs - testing_linux_member role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-testing_linux_member.yml
      - roles/testing_linux_member/.aar_doc.yml
      - roles/testing_linux_member/meta/argument_specs.yml
      - roles/testing_linux_member/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  docs:
    name: Generate testing_linux_member role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_linux_member'
