---
name: Generate Role Docs - rotate_ad_user_password role
'on':
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-rotate_ad_user_password.yml
      - roles/rotate_ad_user_password/.aar_doc.yml
      - roles/rotate_ad_user_password/meta/argument_specs.yml
      - roles/rotate_ad_user_password/meta/main.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-rotate_ad_user_password.yml
      - roles/rotate_ad_user_password/.aar_doc.yml
      - roles/rotate_ad_user_password/meta/argument_specs.yml
      - roles/rotate_ad_user_password/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  docs:
    name: Generate rotate_ad_user_password role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'rotate_ad_user_password'
