---
name: Molecule - testing_domain_controller role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - roles/testing_domain_controller/**
      - '!roles/testing_domain_controller/.aar_doc.yml'
      - '!roles/testing_domain_controller/README.md'
      - '!roles/testing_domain_controller/meta/argument_specs.yml'
      - '!roles/testing_domain_controller/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - roles/testing_domain_controller/**
      - '!roles/testing_domain_controller/.aar_doc.yml'
      - '!roles/testing_domain_controller/README.md'
      - '!roles/testing_domain_controller/meta/argument_specs.yml'
      - '!roles/testing_domain_controller/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  molecule:
    name: Run Molecule test
    uses: trippsoft/github-actions/.github/workflows/molecule.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_domain_controller'
      box: ${{ matrix.box }}
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
