---
name: Molecule - testing_linux_member role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/testing_linux_member/**
      - '!roles/testing_linux_member/.aar_doc.yml'
      - '!roles/testing_linux_member/README.md'
      - '!roles/testing_linux_member/meta/argument_specs.yml'
      - '!roles/testing_linux_member/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/testing_linux_member/**
      - '!roles/testing_linux_member/.aar_doc.yml'
      - '!roles/testing_linux_member/README.md'
      - '!roles/testing_linux_member/meta/argument_specs.yml'
      - '!roles/testing_linux_member/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  molecule:
    name: Run Molecule test
    uses: trippsoft/github-actions/.github/workflows/molecule.yml@main
    with:
      working_directory: 'trippsc2.ad'
      role_name: 'testing_linux_member'
      box: ${{ matrix.box }}
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
          - ubuntu2004_base
